install.packages("tidyverse")
library(tidyverse)
surveys <- read_csv("data/portal_data_joined.csv")
month_day_year <- select(surveys, month, day, year)
year_1981 <- filter(surveys, year == 1981)
filter(surveys, year %in% c(1981:1983))
filter(surveys, year == c(1981, 1982, 1983))
bigfoot_with_weight <- filter(surveys, hindfoot_length > 40 & !is.na(weight))
small_animals <- filter(surveys, weight < 5)
small_animal_ids <- select(small_animals, record_id, plot_id, species_id)
small_animal_ids <- select(filter(surveys, weight < 5), record_id, plot_id, species_id)
small_animal_ids <- filter(surveys, weight < 5) %>% select(record_id, plot_id, species_id)